

title: Jeffrey Ren's Blog
email: 1513699928@qq.com
author: Jeffrey

copyright: "Copyright © 2024 Jeffrey"
copyright-icons:
  - fa-creative-commons
  - fa-creative-commons-by
  - fa-creative-commons-sa

description:
  "Jeffrey Ren's Blog"
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://jeffreyren1.github.io/" # the base hostname & protocol for your site, e.g. https://example.com
favicon: "https://github.com/jeffreyren1/blog/blob/master/assets/images/banners/ico.ico" # the favicon for your site

#可以这么写favicon: "https://github.com/jeffreyren1/blog/raw/master/assets/images/banners/ico.ico" 
#可以这么写favicon: "/assets/images/banners/ico.ico" 


# Yat date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
yat:
  date_format: "%b %d, %Y"
  
last-modified-at:
  date_format: "%F, %T"

# If you want more debug log, you can set true
debug: true

# If you don't want transparent header, you can set false
header_transparent: true

# If you want to change the content width, you can set to another value
content_width: "920px"

# If you want to generate website sitemap, you can set true
sitemap: true

# If you want to change site language, you can set lang option
lang: "en"  # default lang is en
timezone: Asia/Beijing

# Translate languges
# langs refer to https://cloud.google.com/translate/docs/languages
translate_langs:
  - lang: en
    img: https://cdn.countryflags.com/thumbs/united-states-of-america/flag-400.png
    text: English

  - lang: fr
    img: https://cdn.countryflags.com/thumbs/france/flag-400.png
    text: French

  - lang: zh-CN
    img: https://cdn.countryflags.com/thumbs/china/flag-400.png
    text: Chinese Simplified


# You can choose a theme color
# Default theme colors as below:
coolblack: #090a0b
spacegrey: #353535
snowwhite: #ffffff
orangered: #ff5100
greatgold: #f2cb05
greenblue: #389092


# theme_color: "#882250"
theme_color: snowwhite
# brand_color: "#1a8e42"
brand_color: orangered


# You can custom selection style
selection:
  color: "#ff00ff"
  background_color: "yellow"

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is"manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
#
night_mode: "auto"

# Code badge setting
# You can enable or disable the code badge and so on
code_badge:
  enabled: "true"
  color: "#fff"
  background_color: "#ff4e00"
  text_transform: "uppercase"  # ("uppercase", "lowercase", "capitalize")

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - index.html
  - archives.html
  - categories.html
  - tags.html
  - about.html

header_ext_links:
  - title: github
    url: https://github.com/jeffreyren1

# Page default value
defaults:
  home:
    heading: "To be both a speaker of words and a doer of deeds."
    subheading: "Life is a great big canvas, and you should throw all the paint on it you can."
    banner: ""

# Banner default settings
# These banner settings are for global banner default, but you can also
# config it by the front matter for one specific post
banner:
  video: null             # Video banner source
  loop: true              # Video loop
  volume: 0               # Video volume (100% is 1.0)
  start_at: 0             # Video start time
  image: null             # Image banner source
  opacity: 1.0            # Banner opacity (100% is 1.0)
  background: "rgba(0, 0, 0, 0.8)"  # Banner background (Could be a image)
  height: "640px"         # Banner default height
  min_height: null        # Banner minimum height
  heading_style: null     # Custom heading style (e.g. "font-weight: bold; text-decoration: underline")
  subheading_style: null  # Custom subheading style (e.g. color: gold)

# Excerpt settings
excerpt:
  default_image: /assets/images/banners/default-image.jpeg  # Default image when the image style is not none
  image_style: z          # Image layout style (It's value could be none, left, right, top, z, z-reverse)
  image_width: 38.2%      # Image default width
  image_height: 160px     # Image default height
  text_size: 350          # Words default size

# Pagination setting
paginate: 5

# Photo previewer settings (PhotoSwipe 5)
# the options please refer to: https://photoswipe.com/options/
photo_previewer:
 gallery: "section.main"
 children: "a.photo-swipe"
 bgOpacity: 0.8
 padding:
   top: 20
   bottom: 40
   left: 100
   right: 100

# Click to top settings
click_to_top:
  light:
    background_color: "white"
    color: "#454545"
  dark:
    background_color: "#34323d"
    color: "#bbb"

# Disqus comments
disqus:
  shortname: "Jeff"

# Gitment comments
# gitment:
#   username: "Your GitHub username"
#   repo: "The repo to store comments"
#   client_id: "Your client ID"
#   client_secret: "Your client secret"
#   redirect_uri: "Your redirect url"   # If you use a custom domain name

# Utterances comments
# See https://utteranc.es/
# set follow_site_theme true to make utterances' theme follow the site's

# utterances:
#   repo: "owner/repo"
#   issue_term: "title"
#   label: "utterances comment"
#   theme: "github-light"
#   follow_site_theme: true

# Build settings
# highlighter: none
markdown: kramdown
kramdown:
  input: GFM
  entity_output: as_input

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
  - jekyll-last-modified-at
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-autolink_email